name: Tox

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - {
              python-version: "3.8",
              tox-env: "py38",
              os: "ubuntu-latest",
              arch: x64,
            }
          - {
              python-version: "3.9",
              tox-env: "py39",
              os: "ubuntu-latest",
              arch: x64,
            }
          - {
              python-version: "3.10",
              tox-env: "py310",
              os: "ubuntu-latest",
              arch: x64,
            }
          - {
              python-version: "3.11",
              tox-env: "py311",
              os: "ubuntu-latest",
              arch: x64,
            }
          - {
              python-version: "3.12",
              tox-env: "py312",
              os: "ubuntu-latest",
              arch: x64,
            }
          - {
              python-version: "3.12",
              tox-env: "py312",
              os: "ubuntu-latest",
              arch: x86,
            }
          - {
              python-version: "3.12",
              tox-env: "py312",
              os: "ubuntu-latest",
              arch: arm64,
            }
          - {
              python-version: "3.12",
              tox-env: "py312",
              os: "windows-latest",
              arch: x64,
            }
          - {
              python-version: "3.12",
              tox-env: "py312",
              os: "windows-latest",
              arch: x86,
            }
    name: Python ${{ matrix.python-version }} tests (${{ matrix.os }} / ${{ matrix.arch }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libc6:i386
          pip install -r requirements-dev.txt

      - name: Run tests and type checking
        run: tox -e ${{matrix.tox-env }}
